-- This standalone prototype has been superseded by the versioned migration:
--
-- supabase/migrations/202608040001_harden_public_catalog_and_order_creation.sql
--
-- Run that migration in the Supabase SQL Editor. It installs the public-safe
-- catalog functions and the canonical order creation function together so the
-- frontend and database contract cannot drift apart.
