-- Superseded by the atomic, staff-only status workflow in:
-- ../supabase/migrations/202608040003_atomic_order_status_and_stock.sql
--
-- Keep the migration as the executable source of truth so the application,
-- database permissions, and stock behavior are updated together.
