-- Separate customer-facing catalog taxonomy, add reusable materials, and let
-- product photos optionally belong to a product color.

begin;

create table public.departments (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  sort_order integer null,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create unique index departments_name_lower_idx
on public.departments (lower(name));

create table public.product_types (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  sort_order integer null,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create unique index product_types_name_lower_idx
on public.product_types (lower(name));

create table public.materials (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  sort_order integer null,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create unique index materials_name_lower_idx
on public.materials (lower(name));

insert into public.departments (name, slug, sort_order)
values
  ('Women', 'women', 10),
  ('Men', 'men', 20),
  ('Unisex', 'unisex', 30);

insert into public.product_types (name, slug, sort_order)
values
  ('Underwear', 'underwear', 10),
  ('Bra', 'bra', 20),
  ('Pajamas', 'pajamas', 30),
  ('Swimwear', 'swimwear', 40),
  ('Loungewear', 'loungewear', 50);

insert into public.materials (name, slug, sort_order)
values
  ('Cotton', 'cotton', 10),
  ('Modal', 'modal', 20),
  ('Silk', 'silk', 30),
  ('Lace', 'lace', 40),
  ('Satin', 'satin', 50);

alter table public.products
  add column department_id bigint null
    references public.departments(id) on delete restrict,
  add column product_type_id bigint null
    references public.product_types(id) on delete restrict;

update public.products
set department_id = (
  select id from public.departments
  where slug = case when products.category = 'Men' then 'men' else 'women' end
);

update public.products
set product_type_id = (
  select id from public.product_types
  where slug = case
    when products.category = 'Pajamas' then 'pajamas'
    when products.category = 'Swimwear' then 'swimwear'
    else 'underwear'
  end
);

alter table public.products
  alter column department_id set not null,
  alter column product_type_id set not null,
  alter column category drop not null;

alter table public.products
  drop constraint if exists products_category_check;

create index products_department_type_idx
on public.products (department_id, product_type_id)
where deleted_at is null;

create table public.product_materials (
  product_id bigint not null
    references public.products(id) on delete cascade,
  material_id bigint not null
    references public.materials(id) on delete restrict,
  created_at timestamp with time zone not null default now(),
  primary key (product_id, material_id)
);

create index product_materials_material_product_idx
on public.product_materials (material_id, product_id);

alter table public.product_images
  add column color_id bigint null
    references public.colors(id) on delete set null;

create index product_images_product_color_order_idx
on public.product_images (product_id, color_id, display_order);

create trigger set_departments_updated_at
before update on public.departments
for each row execute function public.set_updated_at();

create trigger set_product_types_updated_at
before update on public.product_types
for each row execute function public.set_updated_at();

create trigger set_materials_updated_at
before update on public.materials
for each row execute function public.set_updated_at();

alter table public.departments enable row level security;
alter table public.product_types enable row level security;
alter table public.materials enable row level security;
alter table public.product_materials enable row level security;

revoke all privileges on table public.departments from anon, authenticated;
revoke all privileges on table public.product_types from anon, authenticated;
revoke all privileges on table public.materials from anon, authenticated;
revoke all privileges on table public.product_materials from anon, authenticated;

grant select on table public.departments to authenticated;
grant select on table public.product_types to authenticated;
grant select, insert, update, delete on table public.materials to authenticated;
grant select on table public.product_materials to authenticated;
grant usage, select on sequence public.departments_id_seq to authenticated;
grant usage, select on sequence public.product_types_id_seq to authenticated;
grant usage, select on sequence public.materials_id_seq to authenticated;

create policy staff_read_departments
on public.departments for select to authenticated
using (public.current_user_is_active_staff());

create policy staff_read_product_types
on public.product_types for select to authenticated
using (public.current_user_is_active_staff());

create policy staff_manage_materials
on public.materials for all to authenticated
using (public.current_user_is_active_staff())
with check (public.current_user_is_active_staff());

create policy staff_read_product_materials
on public.product_materials for select to authenticated
using (public.current_user_is_active_staff());

drop function public.get_public_products();
drop function public.get_public_product_images();

create function public.get_public_products()
returns table (
  id bigint,
  slug text,
  name text,
  description text,
  price_mmk bigint,
  department text,
  department_slug text,
  product_type text,
  product_type_slug text,
  availability text
)
language sql
stable
security definer
set search_path = public
as $$
  select
    products.id::bigint,
    products.slug::text,
    products.name::text,
    products.description::text,
    products.price_mmk::bigint,
    departments.name::text,
    departments.slug::text,
    product_types.name::text,
    product_types.slug::text,
    case
      when coalesce(stock.total_quantity, 0) <= 0 then 'Sold out'
      when products.availability = 'Ask staff' then 'Ask staff'
      when products.availability = 'Low stock'
        or stock.total_quantity <= 5 then 'Low stock'
      else 'Available'
    end::text
  from public.products
  join public.departments on departments.id = products.department_id
  join public.product_types on product_types.id = products.product_type_id
  left join lateral (
    select sum(product_variants.quantity) as total_quantity
    from public.product_variants
    where product_variants.product_id = products.id
  ) as stock on true
  where products.is_visible = true
    and products.deleted_at is null
    and departments.is_active = true
    and product_types.is_active = true
  order by products.id;
$$;

create function public.get_public_product_images()
returns table (
  image_id bigint,
  product_id bigint,
  image_url text,
  display_order integer,
  color_id bigint,
  color_name text
)
language sql
stable
security definer
set search_path = public
as $$
  select
    product_images.id::bigint,
    product_images.product_id::bigint,
    product_images.image_url::text,
    product_images.display_order::integer,
    product_images.color_id::bigint,
    colors.name::text
  from public.product_images
  join public.products on products.id = product_images.product_id
  left join public.colors on colors.id = product_images.color_id
  where products.is_visible = true
    and products.deleted_at is null
  order by product_images.product_id, product_images.display_order, product_images.id;
$$;

create function public.get_public_product_materials()
returns table (
  product_id bigint,
  material_id bigint,
  material_name text,
  material_slug text,
  sort_order integer
)
language sql
stable
security definer
set search_path = public
as $$
  select
    product_materials.product_id::bigint,
    materials.id::bigint,
    materials.name::text,
    materials.slug::text,
    materials.sort_order::integer
  from public.product_materials
  join public.materials on materials.id = product_materials.material_id
  join public.products on products.id = product_materials.product_id
  where products.is_visible = true
    and products.deleted_at is null
    and materials.is_active = true
  order by product_materials.product_id, materials.sort_order, materials.id;
$$;

revoke all on function public.get_public_products() from public;
revoke all on function public.get_public_product_images() from public;
revoke all on function public.get_public_product_materials() from public;
grant execute on function public.get_public_products() to anon, authenticated;
grant execute on function public.get_public_product_images() to anon, authenticated;
grant execute on function public.get_public_product_materials() to anon, authenticated;

drop function public.create_product_with_variants(
  text, text, text, text, bigint, text, text, boolean, jsonb
);

drop function public.update_product_info(
  bigint, text, text, bigint, text, text, boolean
);

create function public.create_product_with_variants(
  product_code text,
  product_slug text,
  product_name text,
  product_description text,
  product_price_mmk bigint,
  product_department_id bigint,
  product_type_id bigint,
  product_material_ids bigint[],
  product_availability text,
  product_is_visible boolean,
  product_variants jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_product_id bigint;
  submitted_variant jsonb;
  selected_size public.sizes%rowtype;
  selected_color public.colors%rowtype;
  requested_material_count integer;
  valid_material_count integer;
begin
  if not coalesce(public.current_user_is_active_staff(), false) then
    raise exception using errcode = '42501', message = 'Active staff access is required.';
  end if;

  if not exists (
    select 1 from public.departments
    where id = product_department_id and is_active = true
  ) or not exists (
    select 1 from public.product_types
    where id = product_type_id and is_active = true
  ) then
    raise exception 'Select a valid department and product type.';
  end if;

  select count(distinct requested.id) into requested_material_count
  from unnest(coalesce(product_material_ids, array[]::bigint[])) as requested(id);

  select count(*) into valid_material_count
  from public.materials
  where id = any(coalesce(product_material_ids, array[]::bigint[]))
    and is_active = true;

  if requested_material_count <> valid_material_count then
    raise exception 'Select valid materials.';
  end if;

  insert into public.products (
    code, slug, name, description, price_mmk, department_id,
    product_type_id, availability, is_visible
  ) values (
    trim(product_code), trim(product_slug), trim(product_name),
    trim(product_description), product_price_mmk, product_department_id,
    product_type_id, product_availability, product_is_visible
  ) returning id into new_product_id;

  insert into public.product_materials (product_id, material_id)
  select new_product_id, material_id
  from (
    select distinct unnest(coalesce(product_material_ids, array[]::bigint[])) as material_id
  ) requested;

  if jsonb_typeof(coalesce(product_variants, '[]'::jsonb)) <> 'array' then
    raise exception 'Product variants must be an array.';
  end if;

  for submitted_variant in
    select value from jsonb_array_elements(coalesce(product_variants, '[]'::jsonb))
  loop
    select * into selected_size from public.sizes
    where id = (submitted_variant->>'sizeId')::bigint and is_active = true;

    select * into selected_color from public.colors
    where id = (submitted_variant->>'colorId')::bigint and is_active = true;

    if selected_size.id is null or selected_color.id is null then
      raise exception 'Select valid product options.';
    end if;

    insert into public.product_variants (
      product_id, size, color, size_id, color_id, quantity
    ) values (
      new_product_id, selected_size.name, selected_color.name,
      selected_size.id, selected_color.id,
      (submitted_variant->>'quantity')::integer
    );
  end loop;

  return new_product_id;
end;
$$;

create function public.update_product_info(
  target_product_id bigint,
  new_name text,
  new_description text,
  new_price_mmk bigint,
  new_department_id bigint,
  new_product_type_id bigint,
  new_material_ids bigint[],
  new_availability text,
  new_is_visible boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  requested_material_count integer;
  valid_material_count integer;
begin
  if not coalesce(public.current_user_is_active_staff(), false) then
    raise exception using errcode = '42501', message = 'Active staff access is required.';
  end if;

  if not exists (
    select 1 from public.departments
    where id = new_department_id and is_active = true
  ) or not exists (
    select 1 from public.product_types
    where id = new_product_type_id and is_active = true
  ) then
    raise exception 'Select a valid department and product type.';
  end if;

  select count(distinct requested.id) into requested_material_count
  from unnest(coalesce(new_material_ids, array[]::bigint[])) as requested(id);

  select count(*) into valid_material_count
  from public.materials
  where id = any(coalesce(new_material_ids, array[]::bigint[]))
    and (
      is_active = true
      or exists (
        select 1 from public.product_materials
        where product_id = target_product_id
          and material_id = materials.id
      )
    );

  if requested_material_count <> valid_material_count then
    raise exception 'Select valid materials.';
  end if;

  update public.products set
    name = trim(new_name),
    description = trim(new_description),
    price_mmk = new_price_mmk,
    department_id = new_department_id,
    product_type_id = new_product_type_id,
    availability = new_availability,
    is_visible = new_is_visible
  where id = target_product_id and deleted_at is null;

  if not found then
    raise exception 'Product not found.';
  end if;

  delete from public.product_materials where product_id = target_product_id;

  insert into public.product_materials (product_id, material_id)
  select target_product_id, material_id
  from (
    select distinct unnest(coalesce(new_material_ids, array[]::bigint[])) as material_id
  ) requested;
end;
$$;

revoke all on function public.create_product_with_variants(
  text, text, text, text, bigint, bigint, bigint, bigint[], text, boolean, jsonb
) from public;
revoke all on function public.update_product_info(
  bigint, text, text, bigint, bigint, bigint, bigint[], text, boolean
) from public;

grant execute on function public.create_product_with_variants(
  text, text, text, text, bigint, bigint, bigint, bigint[], text, boolean, jsonb
) to authenticated;
grant execute on function public.update_product_info(
  bigint, text, text, bigint, bigint, bigint, bigint[], text, boolean
) to authenticated;

commit;
