-- Fresh-environment baseline for JuneRose.
--
-- Do not run this file against the existing production project. It captures
-- the original manually-created schema so a new Supabase project can run this
-- migration followed by 202608040001 and later migrations.

begin;

create extension if not exists pg_trgm with schema extensions;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  code text not null,
  slug text not null,
  name text not null,
  description text not null,
  price_mmk bigint not null check (price_mmk >= 0),
  category text not null check (
    category in ('Women', 'Men', 'Pajamas', 'Swimwear')
  ),
  availability text not null default 'Available' check (
    availability in ('Available', 'Low stock', 'Ask staff')
  ),
  is_visible boolean not null default false,
  deleted_at timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint products_code_key unique (code),
  constraint products_slug_key unique (slug)
);

create table if not exists public.sizes (
  id bigint generated by default as identity primary key,
  name text not null,
  sort_order integer null,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create unique index if not exists sizes_name_lower_idx
on public.sizes (lower(name));

create table if not exists public.colors (
  id bigint generated by default as identity primary key,
  name text not null,
  sort_order integer null,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create unique index if not exists colors_name_lower_idx
on public.colors (lower(name));

create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null
    references public.products(id) on delete cascade,
  size text not null,
  color text not null,
  size_id bigint null references public.sizes(id) on delete restrict,
  color_id bigint null references public.colors(id) on delete restrict,
  quantity integer not null default 0 check (quantity >= 0),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create unique index if not exists product_variants_option_key
on public.product_variants (product_id, size_id, color_id)
where size_id is not null and color_id is not null;

create index if not exists product_variants_product_id_idx
on public.product_variants (product_id);

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null
    references public.products(id) on delete cascade,
  image_url text not null,
  display_order integer not null default 0 check (display_order >= 0),
  created_at timestamp with time zone not null default now(),
  constraint product_images_product_order_key
    unique (product_id, display_order)
);

create index if not exists product_images_product_id_idx
on public.product_images (product_id);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  customer_name text not null,
  customer_phone text not null,
  customer_address text not null,
  preferred_contact text not null check (
    preferred_contact in ('Viber', 'Messenger', 'Phone')
  ),
  customer_note text null,
  total_mmk bigint not null check (total_mmk >= 0),
  status text not null default 'pending' check (
    status in (
      'pending',
      'confirmed',
      'preparing',
      'ready',
      'completed',
      'cancelled'
    )
  ),
  stock_reserved_at timestamp with time zone null,
  stock_released_at timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint null references public.products(id) on delete set null,
  product_slug text not null,
  product_name text not null,
  unit_price_mmk bigint not null check (unit_price_mmk >= 0),
  image_url text not null,
  selected_size text not null,
  selected_color text not null,
  quantity integer not null check (quantity > 0),
  line_total_mmk bigint not null check (line_total_mmk >= 0),
  created_at timestamp with time zone not null default now()
);

create index if not exists order_items_order_id_idx
on public.order_items (order_id);

create table if not exists public.inventory_adjustments (
  id bigint generated by default as identity primary key,
  product_variant_id bigint not null
    references public.product_variants(id) on delete restrict,
  quantity_change integer not null check (quantity_change <> 0),
  changed_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamp with time zone not null default now()
);

create index if not exists inventory_adjustments_variant_created_idx
on public.inventory_adjustments (product_variant_id, created_at desc);

create table if not exists public.staff_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.order_notes (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  note text not null check (
    char_length(trim(note)) between 1 and 1000
  ),
  created_by uuid not null default auth.uid()
    references auth.users(id) on delete restrict,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists order_notes_order_created_idx
on public.order_notes (order_id, created_at desc);

create index if not exists products_visible_idx
on public.products (is_visible, id)
where deleted_at is null;

create index if not exists orders_created_at_idx
on public.orders (created_at desc);

create index if not exists orders_status_created_at_idx
on public.orders (status, created_at desc);

create index if not exists orders_total_mmk_idx
on public.orders (total_mmk);

create index if not exists orders_order_number_trgm_idx
on public.orders using gin (order_number gin_trgm_ops);

create index if not exists orders_customer_name_trgm_idx
on public.orders using gin (customer_name gin_trgm_ops);

create index if not exists orders_customer_phone_trgm_idx
on public.orders using gin (customer_phone gin_trgm_ops);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists sizes_set_updated_at on public.sizes;
create trigger sizes_set_updated_at
before update on public.sizes
for each row execute function public.set_updated_at();

drop trigger if exists colors_set_updated_at on public.colors;
create trigger colors_set_updated_at
before update on public.colors
for each row execute function public.set_updated_at();

drop trigger if exists product_variants_set_updated_at
on public.product_variants;
create trigger product_variants_set_updated_at
before update on public.product_variants
for each row execute function public.set_updated_at();

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

drop trigger if exists staff_users_set_updated_at on public.staff_users;
create trigger staff_users_set_updated_at
before update on public.staff_users
for each row execute function public.set_updated_at();

drop trigger if exists order_notes_set_updated_at on public.order_notes;
create trigger order_notes_set_updated_at
before update on public.order_notes
for each row execute function public.set_updated_at();

revoke all on function public.set_updated_at()
from public, anon, authenticated;

create or replace function public.current_user_is_active_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select auth.uid() is not null
    and exists (
      select 1
      from public.staff_users
      where user_id = auth.uid()
        and is_active = true
    );
$$;

revoke all on function public.current_user_is_active_staff()
from public;

grant execute on function public.current_user_is_active_staff()
to authenticated;

create or replace function public.create_product_with_variants(
  product_code text,
  product_slug text,
  product_name text,
  product_description text,
  product_price_mmk bigint,
  product_category text,
  product_availability text,
  product_is_visible boolean,
  product_variants jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_product_id bigint;
  submitted_variant jsonb;
  selected_size public.sizes%rowtype;
  selected_color public.colors%rowtype;
begin
  if not coalesce(public.current_user_is_active_staff(), false) then
    raise exception using
      errcode = '42501',
      message = 'Active staff access is required.';
  end if;

  insert into public.products (
    code,
    slug,
    name,
    description,
    price_mmk,
    category,
    availability,
    is_visible
  )
  values (
    trim(product_code),
    trim(product_slug),
    trim(product_name),
    trim(product_description),
    product_price_mmk,
    product_category,
    product_availability,
    product_is_visible
  )
  returning id into new_product_id;

  if jsonb_typeof(coalesce(product_variants, '[]'::jsonb)) <> 'array' then
    raise exception 'Product variants must be an array.';
  end if;

  for submitted_variant in
    select value
    from jsonb_array_elements(coalesce(product_variants, '[]'::jsonb))
  loop
    select * into selected_size
    from public.sizes
    where id = (submitted_variant->>'sizeId')::bigint
      and is_active = true;

    select * into selected_color
    from public.colors
    where id = (submitted_variant->>'colorId')::bigint
      and is_active = true;

    if selected_size.id is null or selected_color.id is null then
      raise exception 'Select valid product options.';
    end if;

    insert into public.product_variants (
      product_id,
      size,
      color,
      size_id,
      color_id,
      quantity
    )
    values (
      new_product_id,
      selected_size.name,
      selected_color.name,
      selected_size.id,
      selected_color.id,
      (submitted_variant->>'quantity')::integer
    );
  end loop;

  return new_product_id;
end;
$$;

create or replace function public.update_product_info(
  target_product_id bigint,
  new_name text,
  new_description text,
  new_price_mmk bigint,
  new_category text,
  new_availability text,
  new_is_visible boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not coalesce(public.current_user_is_active_staff(), false) then
    raise exception using
      errcode = '42501',
      message = 'Active staff access is required.';
  end if;

  update public.products
  set
    name = trim(new_name),
    description = trim(new_description),
    price_mmk = new_price_mmk,
    category = new_category,
    availability = new_availability,
    is_visible = new_is_visible
  where id = target_product_id
    and deleted_at is null;

  if not found then
    raise exception 'Product not found.';
  end if;
end;
$$;

create or replace function public.adjust_product_stock(
  target_variant_id bigint,
  adjustment_amount integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_variant_id bigint;
begin
  if not coalesce(public.current_user_is_active_staff(), false) then
    raise exception using
      errcode = '42501',
      message = 'Active staff access is required.';
  end if;

  if adjustment_amount = 0 then
    raise exception 'Adjustment cannot be zero.';
  end if;

  update public.product_variants
  set quantity = quantity + adjustment_amount
  where id = target_variant_id
    and quantity + adjustment_amount >= 0
  returning id into updated_variant_id;

  if not found then
    raise exception 'Stock cannot be negative or the variant was not found.';
  end if;

  insert into public.inventory_adjustments (
    product_variant_id,
    quantity_change,
    changed_by
  )
  values (
    updated_variant_id,
    adjustment_amount,
    auth.uid()
  );
end;
$$;

revoke all on function public.create_product_with_variants(
  text,
  text,
  text,
  text,
  bigint,
  text,
  text,
  boolean,
  jsonb
) from public;

revoke all on function public.update_product_info(
  bigint,
  text,
  text,
  bigint,
  text,
  text,
  boolean
) from public;

revoke all on function public.adjust_product_stock(bigint, integer)
from public;

grant execute on function public.create_product_with_variants(
  text,
  text,
  text,
  text,
  bigint,
  text,
  text,
  boolean,
  jsonb
) to authenticated;

grant execute on function public.update_product_info(
  bigint,
  text,
  text,
  bigint,
  text,
  text,
  boolean
) to authenticated;

grant execute on function public.adjust_product_stock(bigint, integer)
to authenticated;

alter table public.products enable row level security;
alter table public.sizes enable row level security;
alter table public.colors enable row level security;
alter table public.product_variants enable row level security;
alter table public.product_images enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.inventory_adjustments enable row level security;
alter table public.staff_users enable row level security;
alter table public.order_notes enable row level security;

revoke all privileges on table public.products from anon;
revoke all privileges on table public.sizes from anon;
revoke all privileges on table public.colors from anon;
revoke all privileges on table public.product_variants from anon;
revoke all privileges on table public.product_images from anon;
revoke all privileges on table public.orders from anon;
revoke all privileges on table public.order_items from anon;
revoke all privileges on table public.inventory_adjustments from anon;
revoke all privileges on table public.staff_users from anon;
revoke all privileges on table public.order_notes from anon;

grant select, insert, update, delete on table public.products to authenticated;
grant select, insert, update, delete on table public.sizes to authenticated;
grant select, insert, update, delete on table public.colors to authenticated;
grant select, insert, update, delete on table public.product_variants
to authenticated;
grant select, insert, update, delete on table public.product_images
to authenticated;
grant select, insert, update, delete on table public.orders to authenticated;
grant select, insert, update, delete on table public.order_items
to authenticated;
grant select, insert, update, delete on table public.inventory_adjustments
to authenticated;
grant select, insert, update, delete on table public.order_notes
to authenticated;

revoke all privileges on table public.staff_users from authenticated;

grant usage, select on all sequences in schema public to authenticated;

drop policy if exists staff_manage_products on public.products;
create policy staff_manage_products
on public.products for all to authenticated
using (public.current_user_is_active_staff())
with check (public.current_user_is_active_staff());

drop policy if exists staff_manage_sizes on public.sizes;
create policy staff_manage_sizes
on public.sizes for all to authenticated
using (public.current_user_is_active_staff())
with check (public.current_user_is_active_staff());

drop policy if exists staff_manage_colors on public.colors;
create policy staff_manage_colors
on public.colors for all to authenticated
using (public.current_user_is_active_staff())
with check (public.current_user_is_active_staff());

drop policy if exists staff_manage_product_variants
on public.product_variants;
create policy staff_manage_product_variants
on public.product_variants for all to authenticated
using (public.current_user_is_active_staff())
with check (public.current_user_is_active_staff());

drop policy if exists staff_manage_product_images on public.product_images;
create policy staff_manage_product_images
on public.product_images for all to authenticated
using (public.current_user_is_active_staff())
with check (public.current_user_is_active_staff());

drop policy if exists staff_manage_orders on public.orders;
create policy staff_manage_orders
on public.orders for all to authenticated
using (public.current_user_is_active_staff())
with check (public.current_user_is_active_staff());

drop policy if exists staff_manage_order_items on public.order_items;
create policy staff_manage_order_items
on public.order_items for all to authenticated
using (public.current_user_is_active_staff())
with check (public.current_user_is_active_staff());

drop policy if exists staff_manage_inventory_adjustments
on public.inventory_adjustments;
create policy staff_manage_inventory_adjustments
on public.inventory_adjustments for all to authenticated
using (public.current_user_is_active_staff())
with check (public.current_user_is_active_staff());

drop policy if exists staff_manage_order_notes on public.order_notes;
create policy staff_manage_order_notes
on public.order_notes for all to authenticated
using (public.current_user_is_active_staff())
with check (public.current_user_is_active_staff());

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'product-images',
  'product-images',
  true,
  5242880,
  array['image/gif', 'image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists staff_insert_product_images on storage.objects;
create policy staff_insert_product_images
on storage.objects for insert to authenticated
with check (
  bucket_id = 'product-images'
  and public.current_user_is_active_staff()
);

drop policy if exists staff_update_product_images on storage.objects;
create policy staff_update_product_images
on storage.objects for update to authenticated
using (
  bucket_id = 'product-images'
  and public.current_user_is_active_staff()
)
with check (
  bucket_id = 'product-images'
  and public.current_user_is_active_staff()
);

drop policy if exists staff_delete_product_images on storage.objects;
create policy staff_delete_product_images
on storage.objects for delete to authenticated
using (
  bucket_id = 'product-images'
  and public.current_user_is_active_staff()
);

commit;
